services:
  fe:
    container_name: fe
    build:
      context: ./apps/fe
      dockerfile: Dockerfile
      target: development
    image: remix-fe-web:latest
    ports:
      - "3010:3010"
    develop:
      watch:
        - action: sync
          path: ./apps/fe/app # ホストマシンのディレクトリ
          target: /usr/src/app # コンテナのディレクトリ
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/fe/package.json
  be:
    build:
      context: ./apps/be
      dockerfile: Dockerfile
      target: development
    image: nestjs-be-api:latest
    ports:
      - 3020:3020
    develop:
      watch:
        - action: sync
          path: ./apps/be/src # ホストマシンのディレクトリ
          target: /usr/workspace/src # コンテナのディレクトリ
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/be/package.json
