services:
  fe:
    container_name: fe
    build:
      context: ./apps/fe
      dockerfile: Dockerfile
      target: development
    image: remix-fe-web:latest
    ports:
      - "3010:3010"
  # be:
  #   build:
  #     context: ./apps/be
  #     dockerfile: Dockerfile
  #   image: nestjs-be-api:latest
  #   ports:
  #     - 3000:3000
