services:
  fe:
    container_name: fe
    build:
      context: ./apps/fe
      dockerfile: Dockerfile
    image: remix-fe-web:latest
    ports:
      # - "5173:5173"
      - "3000:3000"
  # be:
  #   build:
  #     context: ./apps/be
  #     dockerfile: Dockerfile
  #   image: nestjs-be-api:latest
  #   ports:
  #     - 3000:3000
