services:
  fe:
    container_name: fe
    build:
      context: ./apps/fe
      dockerfile: Dockerfile
      target: development
    depends_on:
      - be
      - db
    # ホストマシンから直接アクセスできるように設定
    ports:
      - "3010:3010"
    # ホットリロードのための設定
    develop:
      watch:
        - action: sync
          path: ./apps/fe/app # ホストマシンのディレクトリ
          target: /usr/src/app # コンテナのディレクトリ
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/fe/package.json

  be:
    container_name: be
    build:
      context: ./apps/be
      dockerfile: Dockerfile
      target: development
    depends_on:
      - db
    # ホストマシンから直接アクセスできるように設定
    ports:
      - "3020:3020"
    # ホットリロードのための設定
    develop:
      watch:
        - action: sync
          path: ./apps/be/src # ホストマシンのディレクトリ
          target: /usr/workspace/src # コンテナのディレクトリ
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/be/package.json

  db:
    container_name: db
    build:
      context: ./apps/db
      dockerfile: Dockerfile
      target: development
    expose:
      - 3306  # 他コンテナにポートを開放する
    # ホストマシンから直接アクセスできるように設定
    ports:
      - "3306:3306"
    # データベースの内容を永続化する
    volumes:
      - three-level-architecture-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Password!
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Password!

  schemaspy:
    container_name: schemaspy
    build:
      context: ./apps/schemaspy
      dockerfile: Dockerfile
    platform: linux/amd64 # M1 Macで使うための設定
    # GitHub Pagesで公開することを想定し、docsディレクトリに出力する
    volumes:
      - ./docs:/output
    depends_on:
      - db

volumes:
  three-level-architecture-db:
