services:
  fe:
    container_name: fe
    build:
      context: ./apps/fe
      dockerfile: Dockerfile
      target: production
    image: remix-fe-web:latest
    ports:
      - "3010:3010"
    develop:
      watch:
        - action: sync
          path: ./apps/fe/app # ホストマシンのディレクトリ
          target: /usr/src/app # コンテナのディレクトリ
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/fe/package.json
  # be:
  #   build:
  #     context: ./apps/be
  #     dockerfile: Dockerfile
  #   image: nestjs-be-api:latest
  #   ports:
  #     - 3000:3000
