services:
  fe:
    container_name: fe
    build:
      context: ./apps/fe
      dockerfile: Dockerfile
      target: development
    image: remix-fe-web:latest
    depends_on:
      - be
      - db
    ports:
      - "3010:3010"
    develop:
      watch:
        - action: sync
          path: ./apps/fe/app # ホストマシンのディレクトリ
          target: /usr/src/app # コンテナのディレクトリ
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/fe/package.json
  be:
    container_name: be
    build:
      context: ./apps/be
      dockerfile: Dockerfile
      target: development
    image: nestjs-be-api:latest
    depends_on:
      - db
    ports:
      - "3020:3020"
    develop:
      watch:
        - action: sync
          path: ./apps/be/src # ホストマシンのディレクトリ
          target: /usr/workspace/src # コンテナのディレクトリ
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/be/package.json
  db:
    container_name: db
    build:
      context: ./apps/db
      dockerfile: Dockerfile
      target: development
    image: mysql-db:latest
    ports:
      - "3306:3306"
    volumes:
      - three-level-architecture-db:/var/lib/myslq
    environment:
      - MYSQL_ROOT_PASSWORD=Password!
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Password!
volumes:
  three-level-architecture-db:
